import type { Project } from "./types";

/**
 * Données de démonstration — Mobilier Lacroix (fabrication sur mesure CHR, région lyonnaise).
 * Reconstitue un mois type : ~16 demandes, 3-5 signatures, panier 5-15 k€.
 * Inclut volontairement des fuites du funnel (devis non relancés) pour la démo du diagnostic.
 */
export const PROJECTS: Project[] = [
  // ───────────── NOUVELLES DEMANDES ─────────────
  {
    id: "hmaya",
    client: "Coffee Shop Hmaya",
    type: "coffee-shop",
    city: "Lyon 7e",
    contactName: "Inès Ferhat",
    contactRole: "Gérante",
    channel: "instagram",
    description: "Comptoir d'accueil + étagères murales en chêne clair pour un coffee shop de 40 m².",
    estValue: 5800,
    stage: "nouveau",
    score: 41,
    createdDaysAgo: 2,
    lastActivityDaysAgo: 2,
    devisSent: false,
    nextAction: "Qualifier le besoin et le budget par téléphone",
    exchanges: [
      { id: "e1", daysAgo: 2, type: "email", author: "Inès Ferhat", content: "Bonjour, j'ouvre un coffee shop à la Guillotière, j'aimerais un comptoir sur mesure et des étagères. Vous faites ce genre de projet ?" },
    ],
  },
  {
    id: "potager",
    client: "Le Potager des Halles",
    type: "restaurant",
    city: "Lyon 1er",
    contactName: "Marc Vidal",
    contactRole: "Chef-propriétaire",
    channel: "bouche-a-oreille",
    description: "Réfection de la salle : 14 tables et banquette d'angle, esprit bistrot contemporain.",
    estValue: 11200,
    stage: "nouveau",
    score: 58,
    createdDaysAgo: 4,
    lastActivityDaysAgo: 4,
    devisSent: false,
    nextAction: "Proposer une visite d'atelier",
    exchanges: [
      { id: "e1", daysAgo: 4, type: "appel", author: "Atelier", content: "Appel entrant : recommandé par la Brasserie Georges. Veut refaire toute la salle avant la rentrée de septembre. Budget évoqué : « autour de 10-12 k€ »." },
    ],
  },
  {
    id: "augustin",
    client: "Bar Augustin",
    type: "bar",
    city: "Villeurbanne",
    contactName: "Léa Marchetti",
    contactRole: "Co-gérante",
    channel: "bouche-a-oreille",
    description: "Bar arrière en noyer + tablettes hautes. Projet encore flou, ouverture pas datée.",
    estValue: 6400,
    stage: "nouveau",
    score: 23,
    createdDaysAgo: 8,
    lastActivityDaysAgo: 8,
    devisSent: false,
    nextAction: "Relancer pour qualifier — risque de demande peu mûre",
    exchanges: [
      { id: "e1", daysAgo: 8, type: "email", author: "Léa Marchetti", content: "On réfléchit à ouvrir un bar à vins, on regarde un peu les prix du mobilier sur mesure. Pas pressés." },
    ],
  },

  // ───────────── QUALIFIÉS ─────────────
  {
    id: "silvae",
    client: "Hôtel Silvae",
    type: "hôtel",
    city: "Annecy",
    contactName: "Caroline Brun",
    contactRole: "Directrice",
    channel: "salon",
    description: "Mobilier du lobby (banque d'accueil, fauteuils, tables basses) + têtes de lit pour 12 chambres rénovées.",
    estValue: 15000,
    stage: "qualifie",
    score: 79,
    createdDaysAgo: 11,
    lastActivityDaysAgo: 3,
    devisSent: false,
    nextAction: "Caler la visite d'atelier + prise de mesures sur site",
    exchanges: [
      { id: "e1", daysAgo: 11, type: "visite", author: "Atelier", content: "Rencontre sur notre stand au salon EquipHotel. Très intéressée par le travail du chêne massif." },
      { id: "e2", daysAgo: 7, type: "email", author: "Caroline Brun", content: "Suite au salon : on rénove le lobby + 12 chambres pour l'hiver. Pouvez-vous nous accompagner sur l'ensemble ? Budget validé par la direction." },
      { id: "e3", daysAgo: 3, type: "appel", author: "Atelier", content: "Échange sur le périmètre. Confirme budget ~15 k€ et un calendrier serré (livraison avant décembre). Décisionnaire = elle." },
    ],
  },
  {
    id: "comptoir-md",
    client: "Comptoir Marie-Danton",
    type: "café",
    city: "Lyon 2e",
    contactName: "Hugo Pellet",
    contactRole: "Gérant",
    channel: "recommandation",
    description: "Comptoir en zinc et bois + 6 guéridons. Reprise d'un café avec rénovation partielle.",
    estValue: 7600,
    stage: "qualifie",
    score: 64,
    createdDaysAgo: 9,
    lastActivityDaysAgo: 5,
    devisSent: false,
    nextAction: "Envoyer le book de réalisations puis proposer un RDV atelier",
    exchanges: [
      { id: "e1", daysAgo: 9, type: "appel", author: "Atelier", content: "Recommandé par le Café Lumière (client 2023). Reprend un fonds de commerce, veut un comptoir signature." },
      { id: "e2", daysAgo: 5, type: "email", author: "Hugo Pellet", content: "Merci pour l'appel. Confirmé : ouverture prévue en octobre, budget mobilier autour de 7-8 k€." },
    ],
  },

  // ───────────── VISITE ATELIER / RDV ─────────────
  {
    id: "brotteaux",
    client: "Brasserie des Brotteaux",
    type: "brasserie",
    city: "Lyon 6e",
    contactName: "Daniel Roy",
    contactRole: "Propriétaire",
    channel: "recommandation",
    description: "Banquettes velours + tables marbre/laiton, rénovation complète de la salle (brasserie classée).",
    estValue: 13400,
    stage: "visite",
    score: 81,
    createdDaysAgo: 18,
    lastActivityDaysAgo: 2,
    devisSent: false,
    nextAction: "Finaliser les plans SketchUp pour chiffrage cette semaine",
    exchanges: [
      { id: "e1", daysAgo: 18, type: "appel", author: "Atelier", content: "Veut redonner son lustre à une brasserie 1920. Sensible à l'aspect patrimonial et au sur-mesure." },
      { id: "e2", daysAgo: 9, type: "visite", author: "Atelier", content: "Visite sur site : relevé de mesures, photos. Style art déco souhaité. Très enthousiaste." },
      { id: "e3", daysAgo: 2, type: "visite", author: "Daniel Roy", content: "Est venu à l'atelier voir les finitions et les essences. A adoré les banquettes en velours côtelé. Demande un devis détaillé." },
    ],
  },
  {
    id: "boca-cafe",
    client: "Café de la Cloche (via Ateliers Boca)",
    type: "café",
    city: "Lyon 1er",
    contactName: "Sophie Boca",
    contactRole: "Architecte d'intérieur (prescriptrice)",
    channel: "agenceur",
    description: "Sous-traitance d'agencement : banquettes + comptoir d'un café, sur plans de l'architecte.",
    estValue: 9800,
    stage: "visite",
    score: 72,
    createdDaysAgo: 14,
    lastActivityDaysAgo: 4,
    devisSent: false,
    nextAction: "Recevoir les plans définitifs de l'architecte avant chiffrage",
    exchanges: [
      { id: "e1", daysAgo: 14, type: "email", author: "Sophie Boca", content: "Bonjour, je suis archi d'intérieur, j'ai un projet de café pour lequel je cherche un atelier de confiance pour la fabrication sur mesure. On m'a parlé de vous." },
      { id: "e2", daysAgo: 4, type: "visite", author: "Atelier", content: "RDV à l'atelier avec l'architecte. Excellent contact — pourrait devenir un canal récurrent (elle a 2-3 projets/an)." },
    ],
  },

  // ───────────── DEVIS ENVOYÉ ─────────────
  {
    id: "lumiere",
    client: "Café Lumière",
    type: "café",
    city: "Lyon 1er",
    contactName: "Antoine Charvet",
    contactRole: "Gérant",
    channel: "agenceur",
    description: "Banquettes sur mesure + comptoir en chêne fumé pour l'extension de la salle.",
    estValue: 12000,
    stage: "devis",
    score: 68,
    createdDaysAgo: 21,
    lastActivityDaysAgo: 6,
    devisSent: true,
    nextAction: "Relancer — devis envoyé il y a 6 jours, sans réponse",
    exchanges: [
      { id: "e1", daysAgo: 21, type: "appel", author: "Atelier", content: "Client fidèle (déjà équipé en 2023). Veut prolonger l'esprit de la salle sur l'extension." },
      { id: "e2", daysAgo: 13, type: "visite", author: "Atelier", content: "Prise de mesures sur site, validation des essences." },
      { id: "e3", daysAgo: 6, type: "devis", author: "Atelier", content: "Devis envoyé : 12 000 € HT, délai 7 semaines. Pas de relance programmée." },
    ],
  },
  {
    id: "machonnerie",
    client: "Restaurant La Mâchonnerie",
    type: "restaurant",
    city: "Lyon 5e (Vieux Lyon)",
    contactName: "Paul Génin",
    contactRole: "Propriétaire",
    channel: "bouche-a-oreille",
    description: "20 chaises bistrot + 10 tables en chêne pour un bouchon lyonnais.",
    estValue: 8500,
    stage: "devis",
    score: 55,
    createdDaysAgo: 17,
    lastActivityDaysAgo: 9,
    devisSent: true,
    nextAction: "⚠️ Devis envoyé il y a 9 jours, aucune relance — fuite typique",
    exchanges: [
      { id: "e1", daysAgo: 17, type: "appel", author: "Atelier", content: "Veut remplacer un mobilier vieillissant. Compare avec un fournisseur en série moins cher." },
      { id: "e2", daysAgo: 12, type: "visite", author: "Atelier", content: "Visite atelier, a vu la différence de qualité. Hésite sur le budget." },
      { id: "e3", daysAgo: 9, type: "devis", author: "Atelier", content: "Devis envoyé : 8 500 € HT. Aucun retour depuis. Personne ne l'a relancé." },
    ],
  },
  {
    id: "perchoir",
    client: "Le Perchoir (rooftop)",
    type: "bar",
    city: "Lyon 3e",
    contactName: "Nadia Lemoine",
    contactRole: "Responsable exploitation",
    channel: "salon",
    description: "Mange-debout et bancs d'extérieur traités pour un rooftop saisonnier.",
    estValue: 9300,
    stage: "devis",
    score: 60,
    createdDaysAgo: 15,
    lastActivityDaysAgo: 4,
    devisSent: true,
    nextAction: "Relance prévue : répondre à la question sur le traitement bois extérieur",
    exchanges: [
      { id: "e1", daysAgo: 15, type: "visite", author: "Atelier", content: "Contact sur salon CHR. Besoin de mobilier extérieur résistant." },
      { id: "e2", daysAgo: 7, type: "devis", author: "Atelier", content: "Devis envoyé : 9 300 € HT." },
      { id: "e3", daysAgo: 4, type: "email", author: "Nadia Lemoine", content: "Merci pour le devis. Question : quelle garantie sur la tenue du bois en extérieur ? On veut éviter de refaire dans 2 ans." },
    ],
  },

  // ───────────── NÉGOCIATION / RELANCE ─────────────
  {
    id: "georges",
    client: "Brasserie Georges",
    type: "brasserie",
    city: "Lyon 2e",
    contactName: "Élise Fournier",
    contactRole: "Directrice",
    channel: "recommandation",
    description: "Rénovation d'une partie des banquettes historiques + 8 tables assorties.",
    estValue: 14200,
    stage: "negociation",
    score: 74,
    createdDaysAgo: 27,
    lastActivityDaysAgo: 3,
    devisSent: true,
    nextAction: "Proposer un échelonnement du paiement pour débloquer la signature",
    exchanges: [
      { id: "e1", daysAgo: 27, type: "appel", author: "Atelier", content: "Institution lyonnaise. Veut du sur-mesure fidèle à l'existant." },
      { id: "e2", daysAgo: 20, type: "visite", author: "Atelier", content: "Visite + relevé. Devis détaillé demandé." },
      { id: "e3", daysAgo: 10, type: "devis", author: "Atelier", content: "Devis : 14 200 € HT." },
      { id: "e4", daysAgo: 3, type: "appel", author: "Élise Fournier", content: "On est d'accord sur la qualité. Le budget passe juste au-dessus de l'enveloppe. Possible de discuter le prix ou le paiement ?" },
    ],
  },
  {
    id: "tilia",
    client: "Restaurant Tilia",
    type: "restaurant",
    city: "Lyon 4e (Croix-Rousse)",
    contactName: "Joachim Weber",
    contactRole: "Chef-propriétaire",
    channel: "instagram",
    description: "Comptoir + 8 tables bois brut, esprit nordique. Décision imminente entre 2 ateliers.",
    estValue: 7900,
    stage: "negociation",
    score: 66,
    createdDaysAgo: 22,
    lastActivityDaysAgo: 5,
    devisSent: true,
    nextAction: "Relancer avec une réalisation similaire + délai garanti",
    exchanges: [
      { id: "e1", daysAgo: 22, type: "email", author: "Joachim Weber", content: "Vu vos réalisations sur Instagram, ça correspond à ce que je cherche." },
      { id: "e2", daysAgo: 14, type: "visite", author: "Atelier", content: "Visite atelier, devis remis sur place." },
      { id: "e3", daysAgo: 5, type: "email", author: "Joachim Weber", content: "J'ai un autre devis un peu moins cher. Ce qui me retient chez vous c'est la finition. Vous pouvez tenir le délai de 6 semaines ?" },
    ],
  },

  // ───────────── SIGNÉ (ce mois) ─────────────
  {
    id: "paul-bert",
    client: "Bistrot Paul Bert",
    type: "restaurant",
    city: "Lyon 6e",
    contactName: "Camille Aubert",
    contactRole: "Propriétaire",
    channel: "agenceur",
    description: "Banquettes velours moutarde + 12 tables, projet d'agenceur signé.",
    estValue: 10800,
    stage: "signe",
    score: 100,
    createdDaysAgo: 24,
    lastActivityDaysAgo: 1,
    devisSent: true,
    nextAction: "Lancer la fabrication — acompte reçu",
    exchanges: [
      { id: "e1", daysAgo: 24, type: "email", author: "Atelier", content: "Projet apporté par un agenceur partenaire." },
      { id: "e2", daysAgo: 12, type: "visite", author: "Atelier", content: "Validation maquette et essences." },
      { id: "e3", daysAgo: 1, type: "note", author: "Atelier", content: "Devis signé ✅ — acompte 40 % reçu. Démarrage fabrication semaine prochaine." },
    ],
  },
  {
    id: "moka",
    client: "Maison Moka",
    type: "coffee-shop",
    city: "Lyon 2e",
    contactName: "Yanis Bouchard",
    contactRole: "Fondateur",
    channel: "bouche-a-oreille",
    description: "Comptoir + banc d'attente en frêne pour un coffee shop de spécialité.",
    estValue: 6200,
    stage: "signe",
    score: 100,
    createdDaysAgo: 19,
    lastActivityDaysAgo: 2,
    devisSent: true,
    nextAction: "Planifier la prise de mesures finale",
    exchanges: [
      { id: "e1", daysAgo: 19, type: "appel", author: "Atelier", content: "Recommandé par Coffee Shop Hmaya (réseau coffee specialty)." },
      { id: "e2", daysAgo: 8, type: "visite", author: "Atelier", content: "Visite atelier, choix du frêne huilé." },
      { id: "e3", daysAgo: 2, type: "note", author: "Atelier", content: "Devis signé ✅ — 6 200 € HT." },
    ],
  },
  {
    id: "verriere",
    client: "Hôtel La Verrière",
    type: "hôtel",
    city: "Lyon 6e",
    contactName: "Florence Dax",
    contactRole: "Gérante",
    channel: "salon",
    description: "Têtes de lit et bureaux sur mesure pour 8 chambres.",
    estValue: 9600,
    stage: "signe",
    score: 100,
    createdDaysAgo: 30,
    lastActivityDaysAgo: 3,
    devisSent: true,
    nextAction: "Fabrication en cours — point d'étape prévu",
    exchanges: [
      { id: "e1", daysAgo: 30, type: "visite", author: "Atelier", content: "Contact salon EquipHotel." },
      { id: "e2", daysAgo: 14, type: "devis", author: "Atelier", content: "Devis 9 600 € HT." },
      { id: "e3", daysAgo: 3, type: "note", author: "Atelier", content: "Signé ✅ après une relance bien placée." },
    ],
  },

  // ───────────── PERDU (fuites) ─────────────
  {
    id: "ginkgo",
    client: "Restaurant Ginkgo",
    type: "restaurant",
    city: "Lyon 3e",
    contactName: "Bruno Salas",
    contactRole: "Gérant",
    channel: "bouche-a-oreille",
    description: "12 tables + chaises. Devis envoyé puis jamais relancé.",
    estValue: 8900,
    stage: "perdu",
    score: 0,
    createdDaysAgo: 48,
    lastActivityDaysAgo: 31,
    devisSent: true,
    nextAction: "Perdu — devis sans relance, parti chez un concurrent",
    exchanges: [
      { id: "e1", daysAgo: 48, type: "appel", author: "Atelier", content: "Bon contact, projet clair." },
      { id: "e2", daysAgo: 40, type: "devis", author: "Atelier", content: "Devis 8 900 € HT envoyé." },
      { id: "e3", daysAgo: 31, type: "note", author: "Atelier", content: "❌ Jamais relancé. A signé ailleurs. « On vous avait presque oubliés. »" },
    ],
  },
  {
    id: "zephyr",
    client: "Bar Zéphyr",
    type: "bar",
    city: "Lyon 7e",
    contactName: "Théo Nguyen",
    contactRole: "Co-gérant",
    channel: "instagram",
    description: "Mobilier de terrasse. Budget finalement trop serré.",
    estValue: 5200,
    stage: "perdu",
    score: 0,
    createdDaysAgo: 35,
    lastActivityDaysAgo: 20,
    devisSent: true,
    nextAction: "Perdu sur le prix — cible peu qualifiée au départ",
    exchanges: [
      { id: "e1", daysAgo: 35, type: "email", author: "Théo Nguyen", content: "Vu sur Insta, j'adore mais je ne sais pas si j'ai le budget." },
      { id: "e2", daysAgo: 25, type: "devis", author: "Atelier", content: "Devis 5 200 € HT." },
      { id: "e3", daysAgo: 20, type: "email", author: "Théo Nguyen", content: "Trop cher pour nous cette année, on reportera. Merci quand même !" },
    ],
  },
];

export function getProject(id: string): Project | undefined {
  return PROJECTS.find((p) => p.id === id);
}
